name: simnmt

dependencies:
  - python=3.7
  - pip
  - cffi
  - cython
  - ipython
  - pyyaml
  - six
  - numpy
  - tensorboard
  - tabulate
  - tqdm
  - pillow
  - pip:
    - torch==1.4.0
    - torchvision==0.5.0
    - pytorch-ignite==0.3.0
    - sacrebleu>=1.2.9
    - editdistance==0.4
    - subword_nmt==0.3.5
    - ipdb
    - nltk
    - -e .
